apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    helm.sh/chart: {{ include "echosec.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.rbac.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    jnnkrdb.de/src: github.com/jnnkrdb/echosec
    {{- with .Values.rbac.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: echosec
rules: 
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  - secrets/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list