{{- if .Values.testobjects.cmAnnotations }}
apiVersion: v1
kind: ConfigMap
metadata:  
  {{- with .Values.testobjects.cmAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: test-cm-1
data:
  test: This is a Test
  version: "1"
{{- end }}
