{{- if .Values.testobjects.secAnnotations }}
apiVersion: v1
kind: Secret
metadata:  
  {{- with .Values.testobjects.secAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: test-sec-1
type: Opaque
data:
  test: This is a Test
  version: "1"
{{- end }}
