apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "echosec.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    jnnkrdb.de/src: github.com/jnnkrdb/echosec
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
  name: {{ include "echosec.fullname" . }}-controller
rules: 
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.jnnkrdb.de
  resources:
  - clustersecrets
  verbs:
  #- create
  #- delete
  - get
  - list
  #- patch
  #- update
  - watch
- apiGroups:
  - cluster.jnnkrdb.de
  resources:
  - clustersecrets/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.jnnkrdb.de
  resources:
  - clustersecrets/status
  verbs:
  - get
  - patch
  - update