--- # -------------------------------------------------------------------------------------- ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ include "echosec.fullname" . }}
  labels:
    {{- include "echosec.labels" . | nindent 4 }}
    {{- include "common.labels" ( dict "labels" (list .Values.global.labels .Values.labels) ) | nindent 4 }}
  annotations:
    jnnkrdb.de/src: github.com/jnnkrdb/echosec
    {{- include "common.annotations" ( dict "annotations" (list .Values.global.annotations .Values.annotations) ) | nindent 4 }}
automountServiceAccountToken: true