# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    helm.sh/chart: {{ include "echosec.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.rbac.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    jnnkrdb.de/src: github.com/jnnkrdb/echosec
    {{- with .Values.rbac.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: echosec-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: echosec-election-role
subjects:
- kind: ServiceAccount
  name: echosec
  namespace: {{ .Release.Namespace }}