apiVersion: v1
kind: ServiceAccount
metadata:
  name: echosec
  labels:
    helm.sh/chart: {{ include "echosec.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.rbac.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    jnnkrdb.de/src: github.com/jnnkrdb/echosec
    {{- with .Values.rbac.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
