apiVersion: v1
kind: ConfigMap
metadata:
  labels: 
    helm.sh/chart: {{ include "echosec.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    jnnkrdb.de/src: "github.com/jnnkrdb/echosec"
  name: echosec-yaml
data:
{{- if not (quote .Values.echosecYaml | empty) }}
  echosec.yaml: |
    {{- .Values.echosecYaml | toYaml | nindent 4 }}
{{- else }}
  echosec.yaml: |
    ""
{{- end -}}